export default function robots() {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://www.devservicetech.com';
  
  return {
    rules: {
      userAgent: '*',
      allow: '/',
    },
    // Next.js will automatically create a sitemap index file at /sitemap.xml
    // that points to all the chunked sitemaps generated by sitemap.js
    sitemap: `${baseUrl}/sitemap.xml`,
  };
}
